### ISSUE TITLE
Can CEBRA be used to map discrete data with discrete labels?

### ISSUE THREAD

**Issue by YNCris** [AdaptiveMotorControlLab/CEBRA#151]
Hello! Thank you for providing this amazing tool! I have the data of discreate brain states (like [1,2,3,4,4,3,2,1], different numbers represent different brain states), and I want to map them with my discrete behavior labels. Can CEBRA do that?

**Comment by MMathisLab** [comment]
yes, please see this discussion topic here, and you can use the code directly from github that has the new multi-discrete variable formultion: https://github.com/AdaptiveMotorControlLab/CEBRA/discussions/127
