### ISSUE TITLE
Apply a trained model on a new dataset with different dimension

### ISSUE THREAD

**Issue by snehashis-roy** [AdaptiveMotorControlLab/CEBRA#160]
Hello,
Is it possible to train a model on one dataset, e.g. 3600x200, 3600 =number of timepoints, 200 = number of neurons, to a new dataset with different dimension, such as 3600x150 (i.e. with 150 neurons)?

It looks like cebra.CEBRA.transform requires exact same dimensions.

Thank you.

**Comment by stes** [comment]
Hi @snehashis-roy , this is possible if you use the `adapt=True` argument when fitting the CEBRA model. The reason is that the embedding for the 150 neurons you would like to apply the transform on needs to be fitted first. Please let me know if that addresses the question!

**Comment by stes** [comment]
(please consider the [Discussions](https://github.com/AdaptiveMotorControlLab/CEBRA/discussions) for further questions!)
