### ISSUE TITLE
Python package PR test doesn't pass because of a package compatibility issue

### ISSUE THREAD

**Issue by CeliaBenquet** [AdaptiveMotorControlLab/CEBRA#177]
see https://github.com/AdaptiveMotorControlLab/CEBRA/actions/runs/10940437042/job/30372849824?pr=168 for an example.

I suspect it's a compatibility issue between numpy and sklearn or pandas but I don't know how to solve it. 

From that: https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from; one solution could be to pin down numpy. 

Any ideas @stes @MMathisLab?

**Comment by MMathisLab** [comment]
resolved in https://github.com/AdaptiveMotorControlLab/CEBRA/pull/172!
