### ISSUE TITLE
Can CEBRA use 2d or 3d position as label?

### ISSUE THREAD

**Issue by cnwangy** [AdaptiveMotorControlLab/CEBRA#63]
Can CEBRA use 2d or 3d position as label? If I change the label to 2d delta, an error will be thrown 

> RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1

**Comment by MMathisLab** [comment]
Hi @cnwangy thanks for your question. Could you provide us with example code and failed output, so we can better understand your query, thanks!

**Comment by stes** [comment]
Hi @cnwangy , for now I would recommend to switch to the `time_delta` distribution, then you can use higher dimensional outputs.

We might add support for higher dimensional labels when using the `delta` distribution in the future, right now this is not supported.

**Comment by cnwangy** [comment]
Thanks a lot! I will give a try.
