### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data\\rat_hippocampus/buddy.jl'

### ISSUE THREAD

**Issue by KenR22** [AdaptiveMotorControlLab/CEBRA#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I was trying to run the colab examples, but I am getting this error:
FileNotFoundError: [Errno 2] No such file or directory: 'data\\rat_hippocampus/buddy.jl'

I get the same error on my local installation

### Operating System

Colab

### CEBRA version

0.2.0

### Device type

gpu

### Steps To Reproduce

Run the colab code sequentially upto data loading.

### Relevant log output

```shell
FileNotFoundError: [Errno 2] No such file or directory: 'data\\rat_hippocampus/buddy.jl'
```

### Anything else?

![image](https://github.com/AdaptiveMotorControlLab/CEBRA/assets/11378468/4ea84f52-ebfc-4871-a0f2-2883cc6c9f45)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/daptiveMotorControlLab/CEBRA/blob/main/CODE_OF_CONDUCT.md)

**Comment by KenR22** [comment]
Okay I just saw the figshare download. 
Closing this as solved.

**Comment by MMathisLab** [comment]
It should auto download, so please try to pip install 0.3.0rc1 - the repo is just slightly ahead of the release 🤗
