### ISSUE TITLE
 Apple M1 GPU not supported in CEBRA env created from cebra_paper_m1.yml file

### ISSUE THREAD

**Issue by anna-teruel** [AdaptiveMotorControlLab/CEBRA#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hey :) I have installed CEBRA using the supplied _cebra_paper_m1.yml_ file to run it on Apple M1, macOS Ventura 13.0. Once the installation was completed, I tried to run a training setting _'device = mps'_ but didn't recognize it. Only CUDA or CPU is available. I have followed instructions from CEBRA documentation. When I install CEBRA using pip, it works perfectly. If you need me to provide more details or information let me know!

### Operating System

operating system macOS Ventura 13.0. 

### CEBRA version

cebra version

### Device type

gpu = mps

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/daptiveMotorControlLab/CEBRA/blob/main/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hey Anna 👋 I believe you need to install 0.3.0rc1 as that's support on git but not on pypi yet!

**Comment by stes** [comment]
Hi @anna-teruel , thanks for flagging. Could you confirm if the fix proposed by @MMathisLab fixes the issue?

**Comment by anna-teruel** [comment]
Hi @stes and @MMathisLab, sorry for reaching that late. Yes! Installing 0.3.0rc1 from git works, thanks! Sorry for the misunderstanding, I meant I used pip from a cloned repo. However, the yaml file provided in the docs doesn't support mps yet.

**Comment by MMathisLab** [comment]
Hi @anna-teruel yes, but the full paper reproduction yaml is really not for running CEBRA on an M1 chip, that is really for the issue of installing tensorflow, etc for other packages we benchmark. I opened a PR to separate this to make it more clear, #80, hope that clarifies/helps! You can just run pip install cebra and it will search for the m1/m2 chipset if available.

**Comment by anna-teruel** [comment]
Okay thanks! 🙏
