### ISSUE TITLE
Is CEBRA suitable for Windows system?

### ISSUE THREAD

**Issue by Albertvicient** [AdaptiveMotorControlLab/CEBRA#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Is the CEBRA suitable for Windows System?

### Operating System

operating system

### CEBRA version

cebra version

### Device type

gpu

### Relevant log output

```shell
is the cebra suitable for windows system?
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/daptiveMotorControlLab/CEBRA/blob/main/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @Albertvicient we only tested on Linux and Unix systems (Ubuntu and MacOS), as per our docs: 

https://cebra.ai/docs/installation.html

![image](https://github.com/AdaptiveMotorControlLab/CEBRA/assets/28102185/332dc3a3-3550-492f-9a1d-8320fd2de6a2)

Although if you have gpu support it could work on windows, but we don't officially test this at this time.

**Comment by pderdeyn** [comment]
It works for me on my windows machine. The default conda.yml file works, but for me was CPU only. I'd recommend instead installing pytorch manually first using 
`conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia`
and then installing the rest. If you do install the whole CEBRA environment first, you might have to uninstall pytorch and then run the above command (that's how I set my environment up)
